version: '3'

services:

  shard1svr1:
    container_name: shard1svr1
    image: shard1svr11-mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shard1svr1:/data/db

  # shard1svr2:
  #   container_name: shard1svr2
  #   image: mongo
  #   command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
  #   ports:
  #     - 50002:27017
  #   volumes:
  #     - shard1svr2:/data/db

  # shard1svr3:
  #   container_name: shard1svr3
  #   image: mongo
  #   command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
  #   ports:
  #     - 50003:27017
  #   volumes:
  #     - shard1svr3:/data/db

  # shard2svr1:
  # container_name: shard2svr1
  # image: mongo
  # command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
  # ports:
  #   - 50004:27017
  # volumes:
  #   - shard2svr1:/data/db

  # shard2svr2:
  #   container_name: shard2svr2
  #   image: mongo
  #   command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
  #   ports:
  #     - 50005:27017
  #   volumes:
  #     - shard2svr2:/data/db

  # shard2svr3:
  #   container_name: shard2svr3
  #   image: mongo
  #   command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
  #   ports:
  #     - 50006:27017
  #   volumes:
  #     - shard2svr3:/data/db

  # shard3svr1:
  # container_name: shard3svr1
  # image: mongo
  # command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
  # ports:
  #   - 50007:27017
  # volumes:
  #   - shard3svr1:/data/db

  # shard3svr2:
  #   container_name: shard3svr2
  #   image: mongo
  #   command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
  #   ports:
  #     - 50008:27017
  #   volumes:
  #     - shard3svr2:/data/db

  # shard3svr3:
  #   container_name: shard3svr3
  #   image: mongo
  #   command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
  #   ports:
  #     - 50009:27017
  #   volumes:
  #     - shard3svr3:/data/db

volumes:
  shard1svr1: {}
  # shard1svr2: {}
  # shard1svr3: {}
  # shard2svr1: {}
  # shard2svr2: {}
  # shard2svr3: {}
  # shard3svr1: {}
  # shard3svr2: {}
  # shard3svr3: {}